### ISSUE TITLE
Supporting different request timeouts

### ISSUE THREAD

**Issue by jakeonfire** [HoneyryderChuck/httpx#94]
our use of HTTPX is in a proxy of sorts that connects to dozens of 3rd party APIs, each with their own performance characteristics. we have default request timeouts for most of them, but there are exceptions where we need to specify different timeouts. specifically (for example), when we hit the google sheets get value endpoint, we use timeouts of differing lengths depending on the importance of the request. we hit this endpoint using the same, memoized session but with a request timeout of 15, 30, 60, or 120 seconds.

given this, the comment in the `HTTPX::Timers` code is a bit worrying: https://github.com/HoneyryderChuck/httpx/blob/51ce9d10a4632669d755050b016e26953216116e/lib/httpx/timers.rb#L14-L22

could this be causing issues for us? we are seeing errors from the `falcon` webserver because fibers are not yielding from the scheduler at least once every 30 seconds, as if there are unexpected, long-running, blocking calls. (the issue there is quite complicated and i'd rather not get into it quite yet; currently just wondering if our use-case might be causing problems per the hilighted code comment.)

**Comment by jakeonfire** [comment]
never mind. this doesn't concern our situation because we only issue individual requests at a time.

**Comment by HoneyryderChuck** [comment]
Hey, sorry to hear about it, I took a look at the thread linked in the other issue from async. It'll be hard to assist without logs or a reproduction.  As mentioned before, I have limited experience deploying httpx behind async, and was assuming it handled IO.select calls well, but perhaps that either needs more work, or httpx would need a different async fiber scheduler aware selector via plugin, but that'll be hard to validate without making sure it's because of that.

**Comment by jakeonfire** [comment]
i have so far been unable to create a smaller reproduction app or reproduce it in a locally-running server. but i've made progress on investigating it in production with extra logging and thread dumps.

i caught the app "in the act" of not yielding to the scheduler for several minutes, and it looks like it's looping inside this line: https://github.com/HoneyryderChuck/httpx/blob/51ce9d10a4632669d755050b016e26953216116e/lib/httpx/session.rb#L315

here is a series of stack traces every 30 seconds which shows this: https://github.com/user-attachments/files/20784757/threaddump.summary.txt

it seems like there is some case where that loop never reaches a blocking call like `IO.select` or `IO#wait*`.

**Comment by jakeonfire** [comment]
fwiw we are using the following timeouts (with different numbers, but these are the longest values):
```ruby
timeout = {
  request_timeout: 120,
  read_timeout: 120, # the default is 60 seconds, but we want to depend on :request_timeout which covers read + write
  connect_timeout: 5
}
```

**Comment by trevorturk** [comment]
Super rad, @jakeonfire!

**Comment by HoneyryderChuck** [comment]
hey @jakeonfire thx for keeping up!

Unfortunately, those thread dumps aren't helpful in identifying the root cause, they just confirm the most likely outcome, i.e. some busy loop (for some reason) while handling a request (per fiber).

That monkeypatch, as you already pointed out, patches this behaviour by making `next_tick`(which should have, under normal circumstance, yielded back to the scheduler via `IO.select` or `wait_readable|wait_writable` call) yield back to the scheduler after each call. It at least ensures that a single fiber won't peg the scheduler, It doesn't help identify the root cause though. 

As mentioned earlier, I think we need logs to do that. turning on the debug logs with debug level 2 could help figure out in which state the connection and request are, before the busy loop happens. If you could do that, that'd be great.

Another approach is to somehow "enhance" that monkeypatch of yours to, when in a busy loop (we'd need to figure out how to identify it), log some of state. That would allow us to get some introspection about the state without completely disrupting your application. I'll see if I can come up with something that you can use in production.

A bit of both would be ideal though.

**Comment by jakeonfire** [comment]
would it be possible to enable debug logs in the middle of that loop after the issue occurs or would that be too late?

**Comment by HoneyryderChuck** [comment]
@jakeonfire just push the `gh-94` branch, which contains the fiber id in logs, and logs a specific message with a lot of introspect data, if you can deploy it and leave it running for a while until the issue happens. Again, it's important that, whenever you identify the faulty connection, that all-or-close-to-all data from the respective `fid` (that's the fiber id) is included.

You can also use the `:debug_redact` option, in case you're afraid of disclosing some information in the logs you shouldn't.

**Comment by jakeonfire** [comment]
btw the `debug_redact` option also creates _significantly_ smaller log files, making this easier for me 🙂

**Comment by jakeonfire** [comment]
ok here's one with the missing interests, starting from the first appearance of `fid:1825624`:

[httpx_debug.pid-160986.20250707T193342Z.partial.log](https://github.com/user-attachments/files/21111105/httpx_debug.pid-160986.20250707T193342Z.partial.log)

**Comment by HoneyryderChuck** [comment]
@jakeonfire Thx for the last batch of logs, it was very enlightening about grokking the flow of requests under a fiber scheduler engine. I now have an idea about some of the issues which may have led to this state.

To start, by observing the connection #65280, I noticed the following pattern, where a connection sends the request on one fiber and receives the response on another. Despite it being somewhat inneficient, in and off itself it's not a problem, but it not being immediately deactivated (which happens only after the response would be processed in the original fiber) means that it'll still be accounted for in the selector loop in all fibers using the same session, which explains the "()" registering messages we see. 

The solution could be to deactivate the connection earlier. I still need to investigate whether this is feasible.

This may also be the solution to the loop happens in the end. If you look closely, two connections (65168 and 65792) are being selected on separate fibers, where 65792 is then selected for reading on fiber 1789352, which luckily is the original fiber where the request was sent on, thereby transitioning it to the "inactive" state. The unblocks the loop on fiber 1825624, which then loops on the remaining connection, which at this point is blocked on a busy loop on conn 65168.

conn 65168 on the other hand, has last processed a request on line 20606 (stream id 63) and also processed a ping sent by the peer, but somehow hasn't transitioned to inactive, despite stream id 63 having finalized on fiber 1868944. While processing the next request on the same fiber (stream id 619 of conn 65280), the selector still picks up connection 65168, which eventually leads to the behaviour at the end of the file.

Can I ask whether you're using concurrent calls, similar to `HTTPZ.get(ur1, ur2)`? Not that it's wrong from the UX point of view, but it could explain the behaviour described in the paragraph, and confirm that the suggestion more above could fix the issue.

**Comment by jakeonfire** [comment]
> Can I ask whether you're using concurrent calls, similar to HTTPZ.get(ur1, ur2)?

no we are not explicitly making concurrent calls like that. but they likely happen in the same thread via simultaneous requests just because the server handles a lot of requests at once.

**Comment by HoneyryderChuck** [comment]
> but they likely happen in the same thread via simultaneous requests just because the server handles a lot of requests at once.

On the same thread yes, but not on the same fiber. I'll investigate a bit more to understand where that may come from.

**Comment by jakeonfire** [comment]
side question, when something like this happens:
> a connection sends the request on one fiber and receives the response on another

how does the correct response get returned for the correct request?

**Comment by jakeonfire** [comment]
my previous test ran for a few hours with no issues before i lost the pod to a deploy, but i noticed one of the 2 logs was 17GB (vs 46MB for the other). i was able to tail the last ~1000 lines of that log and it looked normal, so not sure what all that log data was from.

i then got 3 more failures, all in `next_tick`:
- [httpx_debug.pid-24.20250709T213917Z.partial.log](https://github.com/user-attachments/files/21152023/httpx_debug.pid-24.20250709T213917Z.partial.log)
- [httpx_debug.pid-27.20250709T213919Z.partial.log](https://github.com/user-attachments/files/21152027/httpx_debug.pid-27.20250709T213919Z.partial.log)
- [httpx_debug.pid-218725.20250710T002153Z.full.log](https://github.com/user-attachments/files/21152040/httpx_debug.pid-218725.20250710T002153Z.full.log)

the last one was relatively quick, so i sent the whole thing. i don't see anything that looks like a busy loop, so it seems the missing interest issue may be resolved 🚀 i assume there is still some busy loop issue, but different.

**Comment by HoneyryderChuck** [comment]
> the failure is that falcon insists that request-handling fibers yield from the fiber scheduler at least once every 30 seconds, and if not kills the process; there is a [hearbeat async task](https://github.com/socketry/falcon/blob/fa80299923c948e7a4fe9cb792570fd00cc8e1eb/lib/falcon/service/server.rb#L73-L80) that attempts to run every 15 seconds.

I see. It may be a consequence from what I mentioned earlier, i.e. fibers needlessly registering on all sockets instead of meaningful (for that fiber) sockets. Still, this is not very obvious by observing your logs. There's no timestamp associated with the log message, nor an error message coming from falcon saying "process is going down due to missing heartbeat". I do see the fids changing, which means fibers are switching, but perhaps not to the heartbeat timer fiber (not sure how prioritization is handled in this case).

> there is another infrequent error that i believe is unrelated, but worth mentioning

This is not necessarily an issue, as sockets may be closed from a separate thread (like an interrupt), and the `httpx` selector loop is protected against it. I think this is a bug (or perhaps incomplete error handling) in `async`from [this patch](https://github.com/socketry/async/pull/394), as by default, threads, by default, only report on exception, they do not abort. You can verify this with:

```ruby
Thread.start do
  # run once, then uncomment both lines
  # Thread.current.abort_on_exception = true
  # Thread.current.report_on_exception = false

  reader, writer = IO.pipe

  reader.close

  IO.select([reader], nil, nil, 1)
end.value
```

I'm assuming that, in `async`, the exception will have to be yielded to the original fiber using some other mechanism, but I'll let @ioquatix comment on that.

**Comment by ioquatix** [comment]
You should never call `IO.select` with closed IOs, however it was unnecessarily noisy too: https://github.com/socketry/async/commit/d1b106615d525ffbb54bece2372bd999a8cf64ad

This will go out on the next release.

**Comment by HoneyryderChuck** [comment]
> You should never call IO.select with closed IOs 

The IO may not be closed when you call `IO.select`, but it closes meanwhile (and `IO.select` will raise an IOError).

**Comment by jakeonfire** [comment]
unfortunately these changes make the server unstable. one was killed at:
```
#<Async::Task:0x0000000000011650 Reading HTTP/1.1 requests for Async::HTTP::Protocol::HTTP1::Server.>
/usr/local/bundle/gems/async-2.25.0/lib/async/task.rb:105:in 'Fiber#backtrace'
/usr/local/bundle/gems/async-2.25.0/lib/async/task.rb:105:in 'Async::Task#backtrace'
/app/config/initializers/falcon.rb:44:in 'block (4 levels) in Async::Container::Forked::Child.fork'
/app/config/initializers/falcon.rb:41:in 'IO.open'
/app/config/initializers/falcon.rb:41:in 'block (3 levels) in Async::Container::Forked::Child.fork'
/usr/local/bundle/bundler/gems/httpx-b4a3b1d9a093/lib/httpx/plugins/follow_redirects.rb:209:in 'HTTPX::Plugins::FollowRedirects::RequestMethods#response'
/usr/local/bundle/bundler/gems/httpx-b4a3b1d9a093/lib/httpx/session.rb:222:in 'HTTPX::Session#fetch_response'
/usr/local/bundle/bundler/gems/httpx-b4a3b1d9a093/lib/httpx/plugins/retries.rb:104:in 'HTTPX::Plugins::Retries::InstanceMethods#fetch_response'
/usr/local/bundle/bundler/gems/httpx-b4a3b1d9a093/lib/httpx/plugins/follow_redirects.rb:69:in 'HTTPX::Plugins::FollowRedirects::InstanceMethods#fetch_response'
/usr/local/bundle/bundler/gems/httpx-b4a3b1d9a093/lib/httpx/session.rb:317:in 'block in HTTPX::Session#receive_requests'
<internal:kernel>:168:in 'Kernel#loop'
/usr/local/bundle/bundler/gems/httpx-b4a3b1d9a093/lib/httpx/session.rb:312:in 'HTTPX::Session#receive_requests'
/usr/local/bundle/bundler/gems/httpx-b4a3b1d9a093/lib/httpx/session.rb:287:in 'HTTPX::Session#send_requests'
/usr/local/bundle/bundler/gems/httpx-b4a3b1d9a093/lib/httpx/session.rb:106:in 'HTTPX::Session#request'
/app/lib/shimmy/request_helper.rb:508:in 'Shimmy::RequestHelper#make_request'
...
```
with an unremarkable (to me) log: [httpx_debug.pid-24.20250711T194618Z.log](https://github.com/user-attachments/files/21189476/httpx_debug.pid-24.20250711T194618Z.log)

and soon after failed enough k8s health checks in a row to be restarted.
```
  Warning  Unhealthy  5m46s                 kubelet  Readiness probe failed: Get "http://172.18.69.71:3000/status/shallow": read tcp 172.18.74.90:55086->172.18.69.71:3000: read: connection reset by peer
  Warning  Unhealthy  2m35s (x12 over 18m)  kubelet  Readiness probe failed: Get "http://172.18.69.71:3000/status/shallow": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Normal   Killing    2m6s (x4 over 17m)    kubelet  Container shimmy failed liveness probe, will be restarted
```

it also showed an abnormally high number of `Errno::EPIPE: Broken pipe` errors, which happen when the upstream times out the request, indicating everything was running much more slowly. CPU usage was high and memory was low. any ideas?

**Comment by jakeonfire** [comment]
also found a bunch of errors:
```
comparison of HTTPX::Request(plugin)/HTTPX::Plugins::FollowRedirects with HTTPX::Request(plugin)/HTTPX::Plugins::FollowRedirects failed
/usr/local/bundle/bundler/gems/httpx-b4a3b1d9a093/lib/httpx/selector.rb:178:in 'Array#max',
/usr/local/bundle/bundler/gems/httpx-b4a3b1d9a093/lib/httpx/selector.rb:178:in 'block (2 levels) in HTTPX::Selector#select',
/usr/local/bundle/bundler/gems/httpx-b4a3b1d9a093/lib/httpx/loggable.rb:41:in 'HTTPX::Loggable#log',
/usr/local/bundle/bundler/gems/httpx-b4a3b1d9a093/lib/httpx/selector.rb:173:in 'block in HTTPX::Selector#select',
/usr/local/bundle/bundler/gems/httpx-b4a3b1d9a093/lib/httpx/selector.rb:138:in 'Array#delete_if',
/usr/local/bundle/bundler/gems/httpx-b4a3b1d9a093/lib/httpx/selector.rb:138:in 'HTTPX::Selector#select',
/usr/local/bundle/bundler/gems/httpx-b4a3b1d9a093/lib/httpx/selector.rb:38:in 'block in HTTPX::Selector#next_tick',
/usr/local/bundle/bundler/gems/httpx-b4a3b1d9a093/lib/httpx/selector.rb:30:in 'Kernel#catch',
/usr/local/bundle/bundler/gems/httpx-b4a3b1d9a093/lib/httpx/selector.rb:30:in 'HTTPX::Selector#next_tick',
/usr/local/bundle/bundler/gems/httpx-b4a3b1d9a093/lib/httpx/session.rb:317:in 'block (2 levels) in HTTPX::Session#receive_requests',
/usr/local/bundle/bundler/gems/httpx-b4a3b1d9a093/lib/httpx/session.rb:317:in 'Kernel#catch',
/usr/local/bundle/bundler/gems/httpx-b4a3b1d9a093/lib/httpx/session.rb:317:in 'block in HTTPX::Session#receive_requests',
<internal:kernel>:168:in 'Kernel#loop',
/usr/local/bundle/bundler/gems/httpx-b4a3b1d9a093/lib/httpx/session.rb:312:in 'HTTPX::Session#receive_requests',
/usr/local/bundle/bundler/gems/httpx-b4a3b1d9a093/lib/httpx/session.rb:287:in 'HTTPX::Session#send_requests',
/usr/local/bundle/bundler/gems/httpx-b4a3b1d9a093/lib/httpx/session.rb:106:in 'HTTPX::Session#request',
/app/lib/shimmy/request_helper.rb:508:in 'Shimmy::RequestHelper#make_request'
...
```

**Comment by HoneyryderChuck** [comment]
@jakeonfire there was an issue in the logs I added 2/3 days ago, which weren't correctly inferring the most recent stream id (that's the `comparison of` error you see there). I pushed a fix for that.

Is it safe to assume that this was the issue causing the workers to crash?

**Comment by HoneyryderChuck** [comment]
I went ahead and adapte [my hackernews script](https://gitlab.com/os85/httpx/-/blob/gh-94/examples/hackernews_pages.rb?ref_type=heads) to run in normal and "async" mode, to ensure that there wasn't any obvious issue, and it all went well, at least locally.

**Comment by jakeonfire** [comment]
tried it out quick but still getting extra timeouts, broken pipes, and higher CPU 😞 i'll look into it more on Monday, but here's a log in case anything jumps out: [httpx_debug.pid-24.20250712T050751Z.log](https://github.com/user-attachments/files/21192985/httpx_debug.pid-24.20250712T050751Z.log)

**Comment by jakeonfire** [comment]
well this is strange. i tried the newest `gh-94` branch code and now it seems to have a memory leak.

<img width="582" height="226" alt="Image" src="https://github.com/user-attachments/assets/03703e74-ea45-4ab6-8e13-72c40e9d5ab9" />

**Comment by jakeonfire** [comment]
the above happened when i included [the monkeypatch](https://github.com/HoneyryderChuck/httpx/issues/94#issuecomment-3029661889) to call `sleep(0)` on every tick. if i remove that, the falcon processes are killed within a minute or two; so the issue seems even worse 😞 CPU usage is very high and health checks fail regularly. so within 3 minutes i got 3 falcon health-check failure SIGKILLS and then k8s health check failures leading to a pod restart. any ideas?

**Comment by HoneyryderChuck** [comment]
@jakeonfire got sidetracked by issues I found last week. Just to be clear, I didn't expect them to fix your issues, although I didn't expect it to make it worse. The changeset can be found [here](https://gitlab.com/os85/httpx/-/merge_requests/396/commits?commit_id=d64f247e11200bde5e5e114b4206e448d28847aa). There were two main threads being addressed: happy eyeballs somehow got disabled, and object shape performance warnings. As per your logs, your servers aren't multi-homed (I only see IPv4 queries), so we can ignore the former. The changes done to address the latter could result in some more memory consumption (the main change [caches options names (an array of symbols) in the class](https://gitlab.com/os85/httpx/-/merge_requests/396/diffs?commit_id=f64c3ab5990b68f850d0d190535a45162929f0af)), but not in a way that results in memory leaks, at least at a first glance. Do you have some profiling enabled on your side to figure out where the memory surge is coming from? can you post how you're using/calling HTTPX in your source code? 

As for the main issue, I'm back to analysing your logs (shared [here](https://github.com/HoneyryderChuck/httpx/issues/94#issuecomment-3064691850)). It confused me that there was no apparent fiber hogging the main thread, i.e. fid changes frequently, so in theory falcon's heartbeat fiber should have been resumed at some point. However, after analysing each fiber in isolation (took me some time to rearrange the logs), I could spot something weird going on with the following fids:

* 69224, 69224, 70312, 71008, 72368, 73536, 74408 - connection is picked back up (after registering for read) while waiting for a response, but nothing happens after (it should be READ'ing from the socket)
* 69272, 72496 - registered for read after receiving a response and responding to PING frame, which seems wrong (it should have nothing to do), it then gets selected back and that's the last we hear from it

both seem to point at some regression in interest calculation (probably introduced last friday), I'll see if I can reproduce/spot it. It'd be good to know whether, at least, these connections get checked back into the pool (there are no logs for it, I'll add them in the next changeset). Another thing that would be helpful would be to have timestamps for the log messages. @jakeonfire are you using some log collector which automatically adds them, or do I have to temporarily enabled this on httpx logs?

**Comment by jakeonfire** [comment]
> can you post how you're using/calling HTTPX in your source code?

```ruby
module SessionStore
  extend self

  # @return [HTTPX::Session]
  def get(base_url:)
    sessions[base_url] ||= yield
  end

  private

  def sessions
    @_sessions ||= {}
  end
end

def create_session(persistent: true)
  session = HTTPX
  # session = session.with(debug: $stdout, debug_level: 2) # uncomment to see request logs
  origin = nil

  if @base_url.present?
    base_uri = URI(@base_url)
    session = session.with(
      origin: base_uri.origin,
      base_path: base_uri.path
    )
    origin = base_uri.origin
  end

  session = session.plugin(:persistent) if persistent

  session.plugin(:follow_redirects).with(
    redirect_on: ->(redirect_uri) {
      Shimmy::RequestHelper.raise_on_denylist!(redirect_uri, source_origin: origin) || true
    }
  )
end

def session
  @_session ||= if @disable_session_persistence
    create_session(persistent: false)
  else
    SessionStore.get(base_url: @base_url) { create_session }
  end
end

def build_request(method:, endpoint:, query:, body:, headers:, timeout_limit:)
  request_params = if query && !body && method.in?(%i[post patch put])
    {form: query}
  elsif body.is_a?(Hash)
    {params: query, json: body}
  else
    {params: query, body: body}
  end

  timeout = {
    request_timeout: timeout_limit || DEFAULT_REQUEST_TIMEOUT_LIMIT,
    read_timeout: nil, # the default is 60 seconds, but we want to depend on :request_timeout which covers read + write and can be higher than 60 seconds
    connect_timeout: DEFAULT_REQUEST_OPEN_TIMEOUT_LIMIT
  }

  session.build_request(method.to_s.upcase, endpoint, **request_params, headers:, timeout:)
end

request = build_request(method:, endpoint:, query:, body:, headers:, timeout_limit:)
add_auth_to_request(request, method:)
request.headers[:accept] = "application/json" if accept_json
response = session.request(request)
response.raise_for_status unless response.is_a?(::HTTPX::Response)
```

**Comment by jakeonfire** [comment]
the errors are indeed logged to a separate place (to stdout) vs the file logger i'm using for httpx. i'll have to think of how to combine them...

the falcon setup is:
the `docker compose` command is `./falcon.rb`, and that file is:
```ruby
#!/usr/bin/env falcon-host
require "falcon/environment/rack"
require "semantic_logger"

service "shimmy" do
  include Falcon::Environment::Rack

  logger { SemanticLogger["Rails"] }

  # First, preload.rb is loaded, then config.ru.
  append preload "preload.rb"

  count { ENV.fetch("ASYNC_CONTAINER_PROCESSOR_COUNT", 2).to_i }

  endpoint { Async::HTTP::Endpoint.parse("http://0.0.0.0:3000") }
end
```
(you can ignore `SemanticLogger`, it's an internal log-as-JSON formatter that adds some metadata.)

`preload.rb`:
```ruby
require_relative "config/environment"
```

and the rest is a straight-forward rails app in api-only mode that takes inbound requests and makes outbound ones via that request code i had sent before, pretty much 1:1 or 1:a few; in other words its a proxy between our internal app and external APIs.

i will test for the memory leak (with the `sleep(0)` hack) and try to capture an error log (without it).

**Comment by jakeonfire** [comment]
unfortunately the memory leak is still present. it's hard to get a dump because dumps don't get created/saved when the process is force killed (on Ubuntu at least).
<img width="568" height="215" alt="Image" src="https://github.com/user-attachments/assets/b10c4a90-e56f-4014-8cd8-6e1abcfb69c1" />

i tried with the published 1.5.1 gem to be extra sure it wasn't something on my end (since i have been testing a branch with extra changes like saving httpx debug logs to a file, etc.):
<img width="573" height="211" alt="Image" src="https://github.com/user-attachments/assets/2173e4ab-d73c-43bc-b833-ccb1f9cbecb7" />

i've reproduced the health check timeout. **both processes seem to have locked up (or at least they stopped logging from `httpx`) around the same time, 18 and 25 seconds before the health check failures, respectively**:
```
{"time":"2025-07-17T01:01:50+00:00","severity":"warn","oid":67528,"pid":1,"subject":"Async::Container::Forked","message":"Child failed health check!","child":{"name":"shimmy","pid":24,"status":null},"age":30.10036125699844,"health_check_timeout":30}
{"time":"2025-07-17T01:01:50+00:00","severity":"warn","oid":67528,"pid":1,"subject":"Async::Container::Forked","message":"Child failed health check!","child":{"name":"shimmy","pid":27,"status":null},"age":30.0819511370064,"health_check_timeout":30}
```
there were no other logs (warn or error) between boot completion (@ about `2025-07-17T01:00:29.732106`) and the health check failures. the other errors i mentioned i assume are due to server slowness and/or stalls.

here are the httpx debug logs:
- [httpx_debug.pid-24.20250717T010032Z.log](https://github.com/user-attachments/files/21271918/httpx_debug.pid-24.20250717T010032Z.log)
- [httpx_debug.pid-27.20250717T010032Z.log](https://github.com/user-attachments/files/21271920/httpx_debug.pid-27.20250717T010032Z.log)

**Comment by jakeonfire** [comment]
one tricky thing here is i've only been saving httpx debug logs for sessions serving google sheets requests, since those seemed like the most problematic. there are actually more than 10x the requests happening to a handful of 3rd-party APIs, which could be involved in this issue. here is a failure with all the logs, if it's helpful:
```
{"time":"2025-07-15T00:54:01+00:00","severity":"warn","oid":67184,"pid":1,"subject":"Async::Container::Forked","message":"Child failed health check!","child":{"name":"shimmy","pid":24,"status":null},"age":30.049327595006616,"health_check_timeout":30}
{"time":"2025-07-15T00:54:01+00:00","severity":"error","oid":67184,"pid":1,"subject":"Async::Container::Forked","status":"pid 24 exit 1"}
```
[archive.tar.gz](https://github.com/user-attachments/files/21273271/archive.tar.gz) (1.6GB uncompressed!)

**Comment by HoneyryderChuck** [comment]
@jakeonfire thx for the logs. Indeed, I can confirm, I need **all** the relevant httpx logs, not only from a few. The reason is that you're using all them clients in the same process, and they're all using the same fiber scheduler from async. If one of them gets stuck, every one of them gets stuck! To simplify setting up logs on all of them, create a main session first with the common options, then derive the other from there:

```ruby
MyHTTPX = HTTPX.with(debug_level: 2, debug: $stderr)

SOUNDCLOUD = MyHTTPX.with(origin: "https://api.soundcloud.com")

GOOGLE = MyHTTPX.with(origin: "https://api.google.com")
```

> indeed, the last several logs are about missing interests 😅

Yup, you found the hogging fiber! And thanks to the verbose logs, I was able to identify the issue: my changes from one week ago weren't considering the HTTP/1 case well when calculating the current context. I've pushed a patch (see the last commit), if you want to give it a try.

As for the memory leak, I can't figure out from the rest of [these commits](https://gitlab.com/os85/httpx/-/merge_requests/396/commits) what could have been. I'll be "off the grid" until the end of the month though, so I kindly ask you to, at your convenience, to do a "poor man bisect", aka fork the repo, create a branch, and revert-and-deploy each commit one by one until the. issue is reproduced. If you can't make it that's alright, but I'll only be able to come back to this in august probably.

**Comment by jakeonfire** [comment]
for the latest code (with my syntax fix):
good news: no health check failures
bad news: very high memory and CPU, k8s restarts every few minutes

the git bisect is a bit difficult because the processes are killed both for using too much memory and also failing health checks. but here's what i'm looking at (memory limit is 1.5G):
⬇️  `1c5bf34f wip: moar debug logs`:
<img width="575" height="218" alt="Image" src="https://github.com/user-attachments/assets/250061da-f4af-4f41-a8f8-88ec15bfb5c7" />

⬇️ `34ad2e32 added test to reproduce the issue with the skipped query under the fiber scheduler`:
<img width="576" height="227" alt="Image" src="https://github.com/user-attachments/assets/c0ac3e34-b4b5-46e1-aaa2-1824e4d6b259" />
(log size grew _considerably_ more slowly; no k8s health check issues before i ended the test)

⬆️  `cfded052 set fiber context for sent request` 💥💥💥:
<img width="575" height="217" alt="Image" src="https://github.com/user-attachments/assets/28466f86-a25a-40db-a391-c9679de2a4b2" />

⬇️ `375cdf33 improve interest calculation`:
just a flurry of errors:
```
NoMethodError: undefined method 'key?' for nil
      /usr/local/bundle/bundler/gems/httpx-375cdf33c1d9/lib/httpx/connection/http2.rb:65:in 'HTTPX::Connection::HTTP2#interests'
      /usr/local/bundle/bundler/gems/httpx-375cdf33c1d9/lib/httpx/connection.rb:233:in 'HTTPX::Connection#interests'
      /usr/local/bundle/bundler/gems/httpx-375cdf33c1d9/lib/httpx/connection.rb:515:in 'block (2 levels) in HTTPX::Connection#consume'
      ...
```

so it's probably an issue with `cfded052`.

**Comment by jakeonfire** [comment]
i tried the latest working `gh-94` again but without debug logging and it had the same high memory, high error rate, and k8s liveness probe failures (just to eliminate the logging itself as a culprit).

**Comment by HoneyryderChuck** [comment]
@jakeonfire thx for the feedback and help overall.

> for the latest code (with my syntax fix)

thx for identifying the issue and finding a way to test it. I'm still not sure why I didn't find that via CI (or perhaps it did, but I already was in "closing the office" mode and didn't see it). 

> good news: no health check failures (but app runtime is very short so not definitive)

I'd say that the issue may have still been fixed, since the same behaviour wasn't reproduced. but as you mentioned, without finding out the source of the rest of the issues, we should keep a close eye on that.

> so it's probably an issue with cfded052.

thx for pointing me in the direction. Indeed, after careful analysis, I noticed that the changes introduced to deal with http2 connections were holding fibers accidentally, preventing them from being GC'ed This can explain the high memory, while the high CPU may be a byproduct of the memory leak (time mostly spent trying to GC).

I've pushed the changes to the usual branch. I'm still keeping the structure mentioned above around as a `Hash[Fiber, Set[Request]]`, but let's see what the results of your tests show. I'm like to change this hash to index on the fiber object id, although I'm not sure how collision free that is (early assumption).

As usual, if something goes wrong, please collect some logs for analysis.

**Comment by jakeonfire** [comment]
still having the same issues. massive CPU and memory usage.

<img width="1168" height="228" alt="Image" src="https://github.com/user-attachments/assets/9a1e196f-ca7d-4f17-ae6d-c8abeb384729" />

it's tough/impossible to get the logs at the point of complete failure but here is a log from mid-run:
https://assets.ifttt.com/archive.tar.gz

hopefully it gives some insight.

**Comment by HoneyryderChuck** [comment]
@jakeonfire thx for the logs, they were indeed helpful.

I took some time to curate the log file you sent, as most of the noise came from 4 distinct busy loops where a fiber was hogged, once for the `http://ping`, twice for `api.soundcloud.com`, and the last one for `sheets.googleapis.com`.

The first 3 were a busy loop on an HTTP/1.1 connection, which sadly lacked some detail in the introspection logs (I mostly added HTTP/2 data, as I thought it was a more prevalent case). I retroactively added the missing info, but investigating it a bit further, I found out that the buffered requests were not taking part of the current context/fiber calculation, which caused the busy loop in the last 2 cases (and I suspect that it did in the first case too, although the file does not contain the log messages from when it was created, so it's a "99% sure" assumption).

The last one was a harder one to figure out, but after the curation, I could see that some of the selected connections were inactive by the time they were yielded, which was suspicious. after looking at the last associated events with it, I could see that the connection was checked out >30 secs after it had been used, which forced a liveness PING, but in the next fiber, the session was over (after fetching all responses), which deactivates the connections from the selector. This unintendly deactivated that other connection, due to deactivation process only skipping when there are inflight responses, but in this case there was only an inflight PING. So I also added a patch for that.

While the former was an issue introduced as a part of these changes, the latter was an issue that had been already there for a while, but was practically impossible to encounter on a single-fiber scenario. So great that this work is surfacing these kind of issues.

Just pushed the described changes. This should improve CPU usage. I still don't have a great explanation for the memory usage though. But when you try it out, we can see whether it was a byproduct of the issues fixed here or not. I'll see if I can build a small reproduction of your proxy server locally though, as if the mem usage pattern remains the same, I'll need to profile it.

**Comment by jakeonfire** [comment]
i'll give it a longer run tomorrow.

**Comment by jakeonfire** [comment]
> I also added [this commit](https://github.com/HoneyryderChuck/httpx/commit/8d5a8df474a492f7891971697672dfabef25cad1) a bit late yesterday, as I realized that, by holding on to the response, users will indirectly hold on to the request reference, and prevent the fiber from being GC'ed. I'm not sure whether you can confirm whether your deployment contained that commit?

yes, i was working with `8d5a8df4` yesterday.

on my most recent run, i got a falcon health check failure after a little over an hour, unfortunately. so either we have more cases of fiber busy loops and the previous run was a fluke, or the latest changes introduced a new one. i'm not sure if it's related, but there were some errors shortly before. two of these:
```json
  "exception": {
    "class_name": "NoMethodError",
    "message": "undefined method 'after' for nil",
    "stack_trace": [
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/connection.rb:941:in 'block in HTTPX::Connection#set_request_timeout'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/callbacks.rb:12:in 'block in HTTPX::Callbacks#once'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/callbacks.rb:19:in 'block in HTTPX::Callbacks#emit'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/callbacks.rb:19:in 'Array#delete_if'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/callbacks.rb:19:in 'HTTPX::Callbacks#emit'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/request.rb:316:in 'HTTPX::Request#transition'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/connection/http2.rb:189:in 'block in HTTPX::Connection::HTTP2#handle'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/connection/http2.rb:188:in 'Kernel#catch'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/connection/http2.rb:188:in 'HTTPX::Connection::HTTP2#handle'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/connection/http2.rb:127:in 'HTTPX::Connection::HTTP2#send'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/connection.rb:554:in 'HTTPX::Connection#send_request_to_parser'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/connection.rb:324:in 'HTTPX::Connection#send'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/connection.rb:190:in 'block in HTTPX::Connection#merge'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/connection.rb:202:in 'Array#reject!'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/connection.rb:202:in 'block in HTTPX::Connection#purge_pending'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/connection.rb:201:in 'Array#each'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/connection.rb:201:in 'HTTPX::Connection#purge_pending'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/connection.rb:189:in 'HTTPX::Connection#merge'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/connection.rb:161:in 'HTTPX::Connection#coalesce!'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/session.rb:446:in 'HTTPX::Session#coalesce_connections'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/session.rb:408:in 'HTTPX::Session#on_resolver_connection'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/resolver/resolver.rb:156:in 'HTTPX::Resolver::Resolver#resolve_connection'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/callbacks.rb:19:in 'block in HTTPX::Callbacks#emit'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/callbacks.rb:19:in 'Array#delete_if'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/callbacks.rb:19:in 'HTTPX::Callbacks#emit'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/resolver/resolver.rb:111:in 'HTTPX::Resolver::Resolver#emit_resolved_connection'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/resolver/resolver.rb:99:in 'HTTPX::Resolver::Resolver#emit_addresses'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/resolver/native.rb:380:in 'block in HTTPX::Resolver::Native#parse_addresses'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/resolver/native.rb:380:in 'Kernel#catch'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/resolver/native.rb:380:in 'HTTPX::Resolver::Native#parse_addresses'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/resolver/native.rb:284:in 'HTTPX::Resolver::Native#parse'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/resolver/native.rb:248:in 'block in HTTPX::Resolver::Native#dread'",
      "<internal:kernel>:168:in 'Kernel#loop'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/resolver/native.rb:207:in 'HTTPX::Resolver::Native#dread'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/resolver/native.rb:119:in 'block in HTTPX::Resolver::Native#consume'",
      "<internal:kernel>:168:in 'Kernel#loop'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/resolver/native.rb:118:in 'HTTPX::Resolver::Native#consume'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/resolver/native.rb:67:in 'HTTPX::Resolver::Native#call'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/selector.rb:46:in 'block (2 levels) in HTTPX::Selector#next_tick'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/selector.rb:242:in 'HTTPX::Selector#select_one'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/selector.rb:189:in 'HTTPX::Selector#select'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/selector.rb:38:in 'block in HTTPX::Selector#next_tick'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/selector.rb:30:in 'Kernel#catch'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/selector.rb:30:in 'HTTPX::Selector#next_tick'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/session.rb:333:in 'block (2 levels) in HTTPX::Session#receive_requests'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/session.rb:333:in 'Kernel#catch'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/session.rb:333:in 'block in HTTPX::Session#receive_requests'",
      "<internal:kernel>:168:in 'Kernel#loop'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/session.rb:328:in 'HTTPX::Session#receive_requests'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/session.rb:304:in 'HTTPX::Session#send_requests'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/session.rb:106:in 'HTTPX::Session#request'",
      ...
```
and six of these:
```json
  "exception": {
    "class_name": "NoMethodError",
    "message": "undefined method 'select_connection' for nil",
    "stack_trace": [
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/connection.rb:754:in 'HTTPX::Connection#handle_transition'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/connection.rb:668:in 'HTTPX::Connection#transition'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/connection.rb:318:in 'HTTPX::Connection#send'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/connection.rb:190:in 'block in HTTPX::Connection#merge'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/connection.rb:202:in 'Array#reject!'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/connection.rb:202:in 'block in HTTPX::Connection#purge_pending'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/connection.rb:201:in 'Array#each'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/connection.rb:201:in 'HTTPX::Connection#purge_pending'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/connection.rb:189:in 'HTTPX::Connection#merge'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/connection.rb:161:in 'HTTPX::Connection#coalesce!'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/session.rb:446:in 'HTTPX::Session#coalesce_connections'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/session.rb:408:in 'HTTPX::Session#on_resolver_connection'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/resolver/resolver.rb:156:in 'HTTPX::Resolver::Resolver#resolve_connection'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/callbacks.rb:19:in 'block in HTTPX::Callbacks#emit'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/callbacks.rb:19:in 'Array#delete_if'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/callbacks.rb:19:in 'HTTPX::Callbacks#emit'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/resolver/resolver.rb:111:in 'HTTPX::Resolver::Resolver#emit_resolved_connection'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/resolver/resolver.rb:99:in 'HTTPX::Resolver::Resolver#emit_addresses'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/resolver/native.rb:380:in 'block in HTTPX::Resolver::Native#parse_addresses'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/resolver/native.rb:380:in 'Kernel#catch'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/resolver/native.rb:380:in 'HTTPX::Resolver::Native#parse_addresses'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/resolver/native.rb:284:in 'HTTPX::Resolver::Native#parse'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/resolver/native.rb:248:in 'block in HTTPX::Resolver::Native#dread'",
      "<internal:kernel>:168:in 'Kernel#loop'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/resolver/native.rb:207:in 'HTTPX::Resolver::Native#dread'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/resolver/native.rb:119:in 'block in HTTPX::Resolver::Native#consume'",
      "<internal:kernel>:168:in 'Kernel#loop'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/resolver/native.rb:118:in 'HTTPX::Resolver::Native#consume'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/resolver/native.rb:67:in 'HTTPX::Resolver::Native#call'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/selector.rb:46:in 'block (2 levels) in HTTPX::Selector#next_tick'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/selector.rb:242:in 'HTTPX::Selector#select_one'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/selector.rb:189:in 'HTTPX::Selector#select'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/selector.rb:38:in 'block in HTTPX::Selector#next_tick'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/selector.rb:30:in 'Kernel#catch'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/selector.rb:30:in 'HTTPX::Selector#next_tick'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/session.rb:333:in 'block (2 levels) in HTTPX::Session#receive_requests'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/session.rb:333:in 'Kernel#catch'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/session.rb:333:in 'block in HTTPX::Session#receive_requests'",
      "<internal:kernel>:168:in 'Kernel#loop'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/session.rb:328:in 'HTTPX::Session#receive_requests'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/session.rb:304:in 'HTTPX::Session#send_requests'",
      "/usr/local/bundle/bundler/gems/httpx-1fa9783848ba/lib/httpx/session.rb:106:in 'HTTPX::Session#request'",
      ...
```

i also bumped the pod memory limit to 2gb to see if maybe the memory usage is increased but not unbounded. indeterminate results on that, though, since the processes are restarted on health check failure.

**Comment by jakeonfire** [comment]
fwiw the memory usage does look lower without logging

<img width="1460" height="602" alt="Image" src="https://github.com/user-attachments/assets/55ecf260-99b0-4a40-8cba-3c28f495086e" />

**Comment by jakeonfire** [comment]
my logger hack was just an open file handle. i tried using a proper `Logger` using log rotation and the memory usage is slightly better, plateauing around 1.8G.

<img width="1445" height="601" alt="Image" src="https://github.com/user-attachments/assets/2c453560-42ca-47f2-bea6-a0056f44c542" />

log from one of the processes: https://assets.ifttt.com/archive.tar.gz

most recent, relevant errors from `httpx`:
- `"timestamp":"2025-08-08T23:11:35.502339Z","message":"undefined method 'after' for nil"`
- `"timestamp":"2025-08-08T23:23:11.054626Z","message":"undefined method 'after' for nil"`
- `"timestamp":"2025-08-08T23:45:06.876816Z","message":"undefined method 'select_connection' for nil"`
- `"timestamp":"2025-08-09T00:03:46.333576Z","message":"undefined method 'select_connection' for nil"`
- `"timestamp":"2025-08-09T00:13:06.691252Z","message":"undefined method 'after' for nil"`
- `"timestamp":"2025-08-09T00:17:52.072103Z","message":"undefined method 'after' for nil"`
- `"timestamp":"2025-08-09T00:36:31.978803Z","message":"undefined method 'select_connection' for nil"`
- `"timestamp":"2025-08-09T00:58:11.293440Z","message":"undefined method 'select_connection' for nil"`
- `"timestamp":"2025-08-09T01:12:12.370Z","message":"undefined method 'select_connection' for nil"`
- `"timestamp":"2025-08-09T02:13:22.473Z","message":"undefined method 'select_connection' for nil"`

kinda strange i'm only seeing falcon health check failures when i _don't_ enable debug logs 🤔

**Comment by HoneyryderChuck** [comment]
FWIW those errors were due to the last commit from yesterday. I've already reverted it. If the mem usage pattern remains the same, then I was probably trying to fix the wrong thing.

> my logger hack was just an open file handle. i tried using a proper Logger using log rotation and the memory usage is slightly better, plateauing around 1.8G.

Is 1.8G acceptable, compared to your initial usage of httpx prior to having started this thread? As I don't deploy against async myself, I'm not sure what to expect in this case. On the bright side, it's good that it's plateauing somewhere, so we can rule out the possibility of a mem leak.

**Comment by jakeonfire** [comment]
> Is 1.8G acceptable, compared to your initial usage of httpx prior to having started this thread?

i suspect it's mostly due to the logging. when i run without logging the memory usage is comparable to the released gem version, though it doesn't run for more than an hour so this isn't conclusive. but the slope of memory increase is less.

**Comment by HoneyryderChuck** [comment]
Gotcha, that's more reassuring. Lmk then when you run the last state of the changeset again, and do add some logs (ideally from the point where the process is terminated). I'm also assuming that it was taken down due to the health check having failed, I.e. the falcon server never got a response back, and hence could have been CPU bound?

**Comment by HoneyryderChuck** [comment]
Thx for the rundown. Indeed, if health check failures are more uncommon now (are they in the range of failures in the prior version with your patch?), I'd say that we got 99% of it done, and that's good enough for now. 

> the memory usage is a bit high even without logging. it plateaus at just under 2 GB. however i can't say how much better the versioned gem is since it benefits (memory-wise) from regular health check failure restarts.

Indeed, it may be too soon to determine whether that's the expected outcome, or an unwanted side-effect. Given that you're using the `:persistent` plugin, it means that connections aren't terminated, rather they're kept around for reuse. There is no backoffice process to health-check them, i.e. when they're requested for, then depending on a few heuristics, it'll get pinged for liveness, or not, and then if it went down, it'll be reconnected on-the-fly. This means that these instances get retained, and assuming a different connection object for each of the origins you use (and assuming no other change in options), and that, by using the async pool, no other threads are busy doing httpx work, you'll retain as many connection objects as the number of unique origins you're requesting for. If you're not whitelisting them, this may balloon the memory of your process.

But for now, this is just a guess. My suggestion is, I'll merge and eventually release it, and at your own pace, you could try to find a way to profile the memory of the processes, and figure out which type of objects are being retained. I don't have an immediate tip out of my pocket to you, so I'd suggest looking at `memory_profiler`, or `rbspy`, and see whether they'd be useful, and specially across fibers.

Again, thx for the collab and all the trial runs!

**Comment by HoneyryderChuck** [comment]
fixed with bb6907

**Comment by HoneyryderChuck** [comment]
that's great news 🎊 was the prior state still running the feature branch, or did you redeploy 1.5.1 in the meantime?
